# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_table',
            fields=[
                ('csv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_key', models.IntegerField()),
                ('catalog_no', models.CharField(max_length=50)),
                ('catalog_colour', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('catalog_price', models.CharField(max_length=50)),
                ('is_on_sale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='csvfiles',
            fields=[
                ('csv_files_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(null=True, upload_to=b'media/uploads')),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
